"""Bounded owned Hugo preview: edit body, eligibility and links; inspect fresh JSON.
Uses the tiny source generated by check_discovery.py. Restores every fixture edit.
"""
from pathlib import Path
import json,os,re,socket,subprocess,time,urllib.request
RUN=Path(os.environ['SIDERA_CHECK_DIR']).resolve();SOURCE=RUN/'source'
ROOT=Path(__file__).resolve().parents[1]
PORT=int(os.environ.get('SIDERA_PREVIEW_PORT','14512'))
BASE=f'http://127.0.0.1:{PORT}'

def get(path):
    with urllib.request.urlopen(BASE+path,timeout=3) as r:return r.read().decode()

def documents():
    home=get('/preview/')
    url=re.search('data-index="([^"]+)"',home)[1]
    return url,json.loads(get(url))['documents']

def wait(check):
    last=None
    for _ in range(100):
        try:
            result=documents()
            if check(result):return result
        except Exception as e:last=e
        time.sleep(.15)
    (RUN/'preview-last-response.html').write_text(get('/preview/'))
    raise AssertionError(('preview did not update',last))

probe=socket.socket();probe.bind(('127.0.0.1',PORT));probe.close()
files={name:(SOURCE/name).read_text() for name in ('content/journal/b/index.md','content/link-only.md','content/notes/a/index.md','content/notes/_index.md')}
log=open(RUN/'preview.log','w')
process=subprocess.Popen(['hugo','server','--source',str(SOURCE),'--themesDir',str(ROOT/'themes'),'--bind','127.0.0.1','--port',str(PORT),'--baseURL',BASE+'/preview/','--disableFastRender','--noHTTPCache','--destination',str(RUN/'preview-public'),'--cacheDir',str(RUN/'preview-cache')],stdout=log,stderr=subprocess.STDOUT,env={**os.environ,'GOMAXPROCS':'2'})
try:
    before=wait(lambda r: any('/journal/2026/04/14/b/' in d['url'] for d in r[1]))
    assert process.poll() is None
    p=SOURCE/'content/journal/b/index.md';p.write_text(files['content/journal/b/index.md'].replace('Intro marginalia.','LiveRefreshNeedle.').replace('[Cycle](../../notes/a/index.md#native-source)','No cycle now.'))
    updated=wait(lambda r:'LiveRefreshNeedle' in json.dumps(r[1]) and r[0]!=before[0])
    assert not re.search(r'data-content-relations="outgoing"',get('/preview/journal/2026/04/14/b/'))
    p=SOURCE/'content/link-only.md';p.write_text(files['content/link-only.md'].replace('render: link','render: always'))
    wait(lambda r:any(d['url']=='/preview/link-only/' for d in r[1]))
    p.write_text(files['content/link-only.md'])
    wait(lambda r:all(d['url']!='/preview/link-only/' for d in r[1]))
    p=SOURCE/'content/notes/a/index.md';p.write_text(files['content/notes/a/index.md'].replace('params:\n','params:\n  search_index: false\n'))
    wait(lambda r:all(d['url']!='/preview/notes/a/' for d in r[1]))
    p=SOURCE/'content/notes/_index.md';p.write_text(files['content/notes/_index.md'].replace('title: Notes\n','title: Notes\nparams:\n  list_header: false\n'))
    wait(lambda r:all(d['url']!='/preview/notes/' for d in r[1]))
    print('PASS cold Hugo preview + body/link/index opt-out + render link/always eligibility freshness')
finally:
    process.terminate()
    try:process.wait(timeout=10)
    except subprocess.TimeoutExpired:process.kill();process.wait(timeout=5)
    log.close()
    for name,text in files.items():(SOURCE/name).write_text(text)
    probe=socket.socket();probe.setsockopt(socket.SOL_SOCKET,socket.SO_REUSEADDR,1);probe.bind(('127.0.0.1',PORT));probe.close()
